#!/bin/bash

###################
# Ubuntu 14.04.6  #
###################

#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n gpm -v 1.20.4-6.1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n amanda-server -v 1:3.3.3-2ubuntu1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n tftpd -v 0.17-18ubuntu2
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n logwatch -v 7.4.0+svn20130529rev144-1ubuntu1.1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n lm-sensors -v 1:3.3.4-2ubuntu1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n telnetd -v 0.17-36build2

#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n bacula-client -v 5.2.6+dfsg-9.1ubuntu3
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n sysstat -v 10.2.0-1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n powertop -v 2.5-1ubuntu1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n smartmontools -v 6.2+svn3841-1.2ubuntu0.1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n chrony -v 1.29-1ubuntu0.1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n ksh -v 93u+20120801-1ubuntu0.14.04.1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n virt-top -v 1.0.7-1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n nasm -v 2.10.09-1ubuntu0.1

#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n memcached -v 1.4.14-0ubuntu9.3
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n rrdtool -v 1.4.7-2ubuntu5
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n pax -v 1:20120606-2+deb7u1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n rdist -v 6.1.5-18
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n ipvsadm -v 1:1.26-2ubuntu1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n dwz -v 0.11-1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n paps -v 0.6.8-7
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n mksh -v  46-2ubuntu3
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n dstat -v 0.7.2-3build1

#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n units -v 2.02-2
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n supermin -v 4.1.6-1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n marisa -v 0.2.4-5build1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n cdparanoia -v 3.10.2+debian-11
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n mstflint -v 1.4-OFED-1.4.2-1ubuntu1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n transfig -v 1:3.2.5.e-1ubuntu1.1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n mariadb-server -v 5.5.64-1ubuntu0.14.04.1

#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n dovecot-core -v 1:2.2.9-1ubuntu2.6
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n cups -v 1.7.2-0ubuntu1.11
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n sane -v 1.0.14-9
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n quagga -v 0.99.22.4-3ubuntu1.5
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n bind9 -v 1:9.9.5.dfsg-3ubuntu0.19
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n lynx -v 2.8.8pre4-1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n samba -v 2:4.3.11+dfsg-0ubuntu0.14.04.20
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n subversion -v 1.8.8-1ubuntu3.3
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n mc -v  3:4.8.11-1

#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n unbound -v 1.4.22-1ubuntu4.14.04.3
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n mrtg -v 2.17.4-2ubuntu2
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n mgetty-voice -v 1.1.36-2ubuntu1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n lftp -v 4.4.13-1ubuntu0.1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n crash -v 7.0.3-3ubuntu4.5
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_14 -n iptraf-ng -v 1.1.4-1


###################
# Ubuntu 16.04.6  #
###################

python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n gpm -v 1.20.4-6.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n amanda-server -v 1:3.3.6-4.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n tftpd -v 0.17-18ubuntu2
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n logwatch -v 7.4.2-1ubuntu1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n lm-sensors -v 1:3.4.0-2
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n telnetd -v 0.17-40

python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n bacula-client -v 7.0.5+dfsg-4ubuntu0.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n sysstat -v 11.2.0-1ubuntu0.2 # SAME AS 18?
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n powertop -v 2.8-1build1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n smartmontools -v 6.4+svn4214-1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n chrony -v 2.1.1-1ubuntu0.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n ksh -v 93u+20120801-2ubuntu0.16.04.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n virt-top -v 1.0.7-1.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n nasm -v 2.11.08-1ubuntu0.1

python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n memcached -v 1.4.25-2ubuntu1.4
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n rrdtool -v 1.5.5-4
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n pax -v 1:20151013-1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n rdist -v 6.1.5-18
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n ipvsadm -v 1:1.28-3ubuntu0.16.04.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n dwz -v 0.12-1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n paps -v 0.6.8-7ubuntu1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n mksh -v  52c-2
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n dstat -v 0.7.2-4

python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n units -v 2.12-2
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n supermin -v  5.1.14-2ubuntu1.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n marisa -v 0.2.4-8build6
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n cdparanoia -v 3.10.2+debian-11
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n mstflint -v 4.1.0+1.46.gb1cdaf7-1ubuntu3.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n transfig -v 1:3.2.5.e-5ubuntu0.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n mariadb-server -v 10.0.38-0ubuntu0.16.04.1

python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n dovecot-core -v 1:2.2.22-1ubuntu2.10
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n cups -v 2.1.3-4ubuntu0.9
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n sane -v 1.0.14-11
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n quagga -v 0.99.24.1-2ubuntu1.4
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n bind9 -v 1:9.10.3.dfsg.P4-8ubuntu1.14
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n lynx -v 2.8.9dev8-4ubuntu1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n samba -v 2:4.3.11+dfsg-0ubuntu0.16.04.21
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n subversion -v 1.9.3-2ubuntu1.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n mc -v 3:4.8.15-2

python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n unbound -v 1.5.8-1ubuntu1.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n mrtg -v 2.17.4-3ubuntu1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n mgetty-voice -v 1.1.36-2.1+deb8u1build0.16.04.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n lftp -v 4.6.3a-1ubuntu0.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n crash -v 7.2.3+real-1~16.04.1
python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_16 -n iptraf-ng -v 1.1.4-2ubuntu0.16.04.1


###################
# Ubuntu 18.04.6  #
###################

#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n gpm -v 1.20.7-5
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n amanda-server -v 1:3.5.1-1build2
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n tftpd -v 0.17-18ubuntu3
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n logwatch -v 7.4.3+git20161207-2ubuntu1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n lm-sensors -v 1:3.4.0-4
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n telnetd -v 0.17-41

#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n bacula-client -v 9.0.6-1build1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n sysstat -v 11.6.1-1 # SAME AS 18?
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n powertop -v 2.9-0ubuntu1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n smartmontools -v 6.5+svn4324-1 # same as 16?
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n chrony -v 3.2-4ubuntu4.2
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n ksh -v 93u+20120801-3.1ubuntu1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n virt-top -v 1.0.8-1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n nasm -v 2.13.02-0.1

#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n memcached -v 1.5.6-0ubuntu1.1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n rrdtool -v 1.7.0-1build1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n pax -v 1:20171021-2
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n rdist -v 6.1.5-19
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n ipvsadm -v 1:1.28-3ubuntu0.18.04.1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n dwz -v 0.12-2
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n paps -v 0.6.8-7.1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n mksh -v  56c-1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n dstat -v 0.7.3-1

#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n units -v 2.16-1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n supermin -v 5.1.19-2ubuntu1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n marisa -v 0.2.4-8build12
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n cdparanoia -v 3.10.2+debian-13
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n mstflint -v 4.8.0-2
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n transfig -v 1:3.2.6a-6ubuntu1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n mariadb-server -v 10.0.38-0ubuntu0.16.04.1

#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n dovecot-core -v 1:2.2.33.2-1ubuntu4.3
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n cups -v 2.2.7-1ubuntu2.6
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n sane -v 1.0.14-12build1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n quagga -v 1.2.4-1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n bind9 -v 1:9.11.3+dfsg-1ubuntu1.8
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n lynx -v 2.8.9dev16-3
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n samba -v 2:4.7.6+dfsg~ubuntu-0ubuntu2.11
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n subversion -v 1.9.7-4ubuntu1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n mc -v 3:4.8.19-1

#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n unbound -v 1.6.7-1ubuntu2.2
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n mrtg -v 2.17.4-4.1ubuntu1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n mgetty-voice -v 1.1.36-3.1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n lftp -v 4.8.1-1ubuntu0.1
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n crash -v 7.2.1-1ubuntu2
#python3 automated_cs_record.py -t /home/ubuntu/praxi/vers_18 -n iptraf-ng -v 1:1.1.4-6
